import { format } from 'date-fns';
import { TimelineResult, TimelineDay, TimelineSession, OverallRating } from '../types';

/**
 * Format timeline as shareable Markdown
 */
export function formatTimelineMarkdown(timeline: TimelineResult): string {
  const lines: string[] = [];

  // Header
  lines.push('# Vibe-Check Timeline Report');
  lines.push('');

  // Overview
  const dateRange = `${format(timeline.from, 'MMM d')} - ${format(timeline.to, 'MMM d, yyyy')}`;
  const activeHours = Math.round(timeline.totalActiveMinutes / 60);
  lines.push(`**Period:** ${dateRange} (${timeline.totalDays} days)`);
  lines.push(`**Active Time:** ~${activeHours} hours`);
  lines.push(`**Commits:** ${timeline.totalCommits} (${timeline.totalFeatures} features, ${timeline.totalFixes} fixes)`);
  lines.push(`**Sessions:** ${timeline.sessions.length}`);
  lines.push('');

  // Trend sparkline (text representation)
  const trendStr = timeline.trend.map(score => {
    if (score === null) return '▁';
    if (score >= 80) return '█';
    if (score >= 60) return '▆';
    if (score >= 40) return '▄';
    return '▂';
  }).join('');
  lines.push(`**Trend:** \`${trendStr}\``);
  lines.push('');

  // Summary stats table
  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Flow States | ${timeline.flowStates} |`);
  lines.push(`| Debug Spirals | ${timeline.totalSpirals} |`);
  lines.push(`| Total XP | ${timeline.totalXp} |`);
  if (timeline.postDeleteSprint?.detected) {
    lines.push(`| Post-Delete Sprint | ${timeline.postDeleteSprint.velocityIncrease}x velocity |`);
  }
  if (timeline.detours?.detected) {
    lines.push(`| Detours | ${timeline.detours.detours.length} (${timeline.detours.totalTimeLost}m lost) |`);
  }
  if (timeline.lateNightSpirals?.detected) {
    lines.push(`| Late-Night Spirals | ${timeline.lateNightSpirals.spirals.length} (${timeline.lateNightSpirals.totalDuration}m) |`);
  }
  if (timeline.thrashing?.detected) {
    lines.push(`| Thrashing Files | ${timeline.thrashing.files.length} |`);
  }
  lines.push('');

  // Days breakdown
  lines.push('## Daily Breakdown');
  lines.push('');

  for (const day of timeline.days) {
    lines.push(formatDayMarkdown(day));
    lines.push('');
  }

  // Insights
  lines.push('## Insights');
  lines.push('');

  if (timeline.postDeleteSprint?.detected) {
    lines.push(`- ⚡ **Post-delete sprint:** ${timeline.postDeleteSprint.message}`);
  }
  if (timeline.flowStates > 0) {
    const avgFlowDuration = timeline.sessions
      .filter(s => s.flowState)
      .reduce((sum, s) => sum + s.duration, 0) / timeline.flowStates;
    lines.push(`- 🌊 **Flow states:** ${timeline.flowStates} detected (avg ${Math.round(avgFlowDuration)} min)`);
  }
  if (timeline.detours?.detected) {
    lines.push(`- 🚧 **Detours:** ${timeline.detours.message}`);
  }
  if (timeline.lateNightSpirals?.detected) {
    lines.push(`- 🌙 **Late-night spirals:** ${timeline.lateNightSpirals.message}`);
  }
  if (timeline.thrashing?.detected) {
    lines.push(`- 🔄 **Thrashing:** ${timeline.thrashing.message}`);
  }
  if (timeline.totalSpirals > 0) {
    lines.push(`- ⚠️ **Debug spirals:** ${timeline.totalSpirals} detected`);
  }

  // Productivity ratio
  const wallClockHours = timeline.totalDays * 24;
  const efficiencyPercent = Math.round((activeHours / wallClockHours) * 100);
  lines.push(`- ⏱️ **Active time:** ${activeHours}h of ${wallClockHours}h (${efficiencyPercent}% efficiency)`);

  // Best day
  const bestDay = timeline.days.reduce((best, day) =>
    (day.dayScore || 0) > (best.dayScore || 0) ? day : best
  );
  if (bestDay.dayScore && bestDay.dayScore >= 80) {
    lines.push(`- 🏆 **Best day:** ${bestDay.displayDate} (${bestDay.dayScore}%)`);
  }

  lines.push('');

  // Footer
  lines.push('---');
  lines.push(`*Generated by [vibe-check](https://github.com/boshu2/vibe-check) on ${format(new Date(), 'yyyy-MM-dd HH:mm')}*`);

  return lines.join('\n');
}

/**
 * Format a single day for markdown
 */
function formatDayMarkdown(day: TimelineDay): string {
  const lines: string[] = [];
  const ratingEmoji = getRatingEmoji(day.dayRating);
  const trophy = day.dayRating === 'ELITE' ? ' 🏆' : '';

  lines.push(`### ${day.displayDate} — ${day.dayScore}% ${day.dayRating}${trophy}`);
  lines.push('');
  lines.push(`${day.sessions.length} session${day.sessions.length > 1 ? 's' : ''}, ${day.totalCommits} commits, ${day.spiralCount} spirals, +${day.totalXp} XP`);
  lines.push('');

  // Session list
  for (const session of day.sessions) {
    const timeRange = `${format(session.start, 'HH:mm')}-${format(session.end, 'HH:mm')}`;
    const durationStr = formatDuration(session.duration);
    const flowIcon = session.flowState ? ' 🌊' : '';
    const spiralIcon = session.spirals.length > 0 ? ' ⚠️' : '';

    // Get main work summary
    const featCount = session.commits.filter(c => c.type === 'feat').length;
    const fixCount = session.commits.filter(c => c.type === 'fix').length;

    let workSummary = '';
    if (featCount > 0) {
      const firstFeat = session.commits.find(c => c.type === 'feat');
      workSummary = firstFeat ? truncate(firstFeat.subject, 50) : `${featCount} features`;
    } else if (fixCount > 0) {
      workSummary = `${fixCount} fix${fixCount > 1 ? 'es' : ''}`;
    } else {
      const first = session.commits[0];
      workSummary = truncate(first.subject, 50);
    }

    lines.push(`- **${timeRange}** (${durationStr})${flowIcon}${spiralIcon}: ${workSummary}`);
  }

  return lines.join('\n');
}

/**
 * Get emoji for rating
 */
function getRatingEmoji(rating: OverallRating): string {
  switch (rating) {
    case 'ELITE': return '🟢';
    case 'HIGH': return '🔵';
    case 'MEDIUM': return '🟡';
    case 'LOW': return '🔴';
  }
}

/**
 * Format duration in human-readable form
 */
function formatDuration(minutes: number): string {
  if (minutes < 60) return `${minutes}m`;
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`;
}

/**
 * Truncate string with ellipsis
 */
function truncate(str: string, maxLen: number): string {
  if (str.length <= maxLen) return str;
  return str.substring(0, maxLen - 1) + '…';
}
